name: super_enum
description: Create super-powered enums similar to sealed classes in Kotlin.
version: 0.4.2
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  equatable: ^1.1.0

# Adding dev dependencies
# just for showcasing an example
dev_dependencies:
  http: ^0.12.0+2
  build_runner: ^1.7.1
  super_enum_generator:
    path: ../super_enum_generator

