name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.6.1
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
  super_enum: ^0.5.1
  source_gen: ^1.0.0
  analyzer: ^4.6.0
  build: ^2.0.0
  code_builder: ^4.2.0
  dart_style: ^2.0.0

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.3
  source_gen_test: ^0.1.1+1
