name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.3.0
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
  super_enum:
    path: ../super_enum
  source_gen: ^0.9.4+6
  analyzer: '>=0.36.0 <0.40.0'
  build: '>=0.12.6 <2.0.0'
  code_builder: ^3.2.0
  dart_style: ^1.3.3

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.7.1
  source_gen_test: ^0.1.0+6